print("\n F1 Technical")
first_name = input("First Name: ")
middle_name = input("Middle Name: ")
last_name = input("last Name: ")
birthday = input("MM/DD/YY: ")
gender = input("Male/Female: ")
address = input("Address: ")
course = input("course: ")
year_level = input("Year level: ")

print("First Name: ", first_name)
print("Middle Name:", middle_name)
print("Last Name", last_name)
print("Birthday", birthday)
print("Gender", gender)
print("Address", address)
print("Course", course)
print("Year Level", year_level)
